### ISSUE TITLE
isEncodingLinearPcm return false for FOS 5 device (AFTT)

### ISSUE THREAD

**Issue by xiaoluluxian** [amzn/exoplayer-amazon-port#122]
### ExoPlayer Version

2.13.3

### Devices that reproduce the issue

FireTV Tank FOS 5 device running Android API 22

### Devices that do not reproduce the issue

FireTV Mantis FOS 6 device running Android API 25

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play the media in app causing the error below.
```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:589)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:41)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:525)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:485)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.updateOutputFormatForTime(MediaCodecRenderer.java:649)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:838)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:954)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:480)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

DefaultAudioSink.configure actually checking isEncodingLinearPcm() and this return false causing Assertions.checkArgument throw IllegalArgumentException

### Expected result

Media plays successfully

### Actual result

Exoplayer throws error below

```
E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:589)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:41)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.configure(DefaultAudioSink.java:525)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onOutputFormatChanged(MediaCodecAudioRenderer.java:485)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.updateOutputFormatForTime(MediaCodecRenderer.java:649)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:838)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:954)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:480)
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by abshankr** [comment]
Issue was due to an incorrect import of ExoPlayer dependencies. Issue was resolved after manually importing all the required ExoPlayer dependencies in the app.
