### ISSUE TITLE
EXTERNAL_SURROUND_SOUND_ENABLED accessor causes crash in Instant Apps

### ISSUE THREAD

**Issue by JonWatson** [amzn/exoplayer-amazon-port#24]
When running the Amazon ExoPlayer port on a Google Instant App, the accessing of Settings.Global.getInt(resolver, EXTERNAL_SURROUND_SOUND_ENABLED, 0) in AudioCapabilities.java causes a crash because certain properties like this are not accessible from the Instant App for security reasons.

To reproduce, create an instant app that uses the Amazon ExoPlayer port and play a video with Audio capabilities.

api "com.amazon.android:exoplayer:r2.5.4"

Google Pixel - Android 8.0

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.nousguide.android.rbtv.debug, PID: 16082
                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nousguide.android.rbtv.debug/com.nousguide.android.rbtv.applib.MainActivity}: java.lang.SecurityException: Setting external_surround_sound_enabled is not accessible from ephemeral package com.nousguide.android.rbtv.debug
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                   Caused by: java.lang.SecurityException: Setting external_surround_sound_enabled is not accessible from ephemeral package com.nousguide.android.rbtv.debug
                                                                                      at android.os.Parcel.readException(Parcel.java:1942)
                                                                                      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                                      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                                      at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
                                                                                      at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1902)
                                                                                      at android.provider.Settings$Global.getStringForUser(Settings.java:10061)
                                                                                      at android.provider.Settings$Global.getString(Settings.java:10050)
                                                                                      at android.provider.Settings$Global.getInt(Settings.java:10229)
                                                                                      at com.google.android.exoplayer2.audio.AudioCapabilities.isSurroundSoundEnabledV17(AudioCapabilities.java:84)
                                                                                      at com.google.android.exoplayer2.audio.AudioCapabilities.getCapabilities(AudioCapabilities.java:70)
                                                                                      at com.google.android.exoplayer2.audio.AudioCapabilities.getCapabilities(AudioCapabilities.java:63)
                                                                                      at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioRenderers(DefaultRenderersFactory.java:219)
                                                                                      at com.rbtv.core.player.exoplayer.ExoPlayerWrapper$2.buildAudioRenderers(ExoPlayerWrapper.java:317)
                                                                                      at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:145)
                                                                                      at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:130)
                                                                                      at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:158)
                                                                                      at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:143)
                                                                                      at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:129)
                                                                                      at

**Comment by peddisri** [comment]
@JonWatson Did you find a way to work around this? Is that the reason you closed the issue?
