### ISSUE TITLE
PlayReady Smooth Streaming not playing

### ISSUE THREAD

**Issue by mlykotom** [amzn/exoplayer-amazon-port#5]
Hi,
I've been trying to play DRM video with SmoothStreaming and PlayReady which crashes before video starts playing.

Tested on Fire TV with Fire Os 5.2.1.0 (550145120)

Error is reproducible in the demo player -> Smooth Streaming -> Super speed (Play Ready).
Smooth Streaming without Play Ready works fine. Also works fine on Android TV with original ExoPlayer library.

**<----Logcat---->**
07-28 16:39:49.072 7039-7836/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                        android.media.MediaCodec$CodecException: Error 0x8004d817
                                                                                            at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                            at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:978)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:754)
                                                                                            at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:551)
                                                                                            at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                                            at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                            at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
07-28 16:39:49.073 7039-7836/com.google.android.exoplayer.demo I/OMX.MTK.VIDEO.DECODER.AVC.secure-MediaCodecTrackRenderer: releaseCodec
07-28 16:39:49.073 7039-7836/com.google.android.exoplayer.demo D/MediaCodec: stop : turning off cabl
07-28 16:39:49.073 7039-7836/com.google.android.exoplayer.demo I/MediaCodec: setContextAdaptiveBacklight
07-28 16:39:49.073 7039-7836/com.google.android.exoplayer.demo E/MediaCodec: setContextAdaptiveBacklight: Could not open file to turn on/off CABL err = No such file or directory
07-28 16:39:49.073 7039-7836/com.google.android.exoplayer.demo I/MediaCodec: setContextAdaptiveBacklight: Best effort to turn context adaptive backlight OFF
07-28 16:39:49.079 7039-7039/com.google.android.exoplayer.demo E/EventLogger: playerFailed [1.67]
                                                                              com.google.android.exoplayer.ExoPlaybackException: android.media.MediaCodec$CodecException: Error 0x8004d817
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                               Caused by: android.media.MediaCodec$CodecException: Error 0x8004d817
                                                                                  at android.media.MediaCodec.native_queueSecureInputBuffer(Native Method)
                                                                                  at android.media.MediaCodec.queueSecureInputBuffer(MediaCodec.java:978)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:754)
                                                                                  at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:551)
                                                                                  at com.google.android.exoplayer.SampleSourceTrackRenderer.doSomeWork(SampleSourceTrackRenderer.java:129)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:434)
                                                                                  at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                  at android.os.Looper.loop(Looper.java:135) 
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                  at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .
07-28 16:39:49.083 7039-7858/com.google.android.exoplayer.demo E/IMGSRV: :0: MTKSecureUnref: can not to do MTKSecureUnref, because ghSession == NULL .

**Comment by peddisri** [comment]
The SuperSpeed Sample in ExoPlayer Demo would not work straight away on Fire TV Devices because it does not support playback of encrypted Audio without specific customization.. 

Please refer to https://developer.amazon.com/public/solutions/devices/fire-tv/docs/media-specifications#drm for further details. 

Using this link, you would need to contact Amazon for getting information about specific customization required to play encrypted Audio.
